import type { Metadata } from "next";
import { Geist, Geist_Mono, Yeseva_One, Quicksand, Courier_Prime } from "next/font/google";
import { config } from '@fortawesome/fontawesome-svg-core'
import '@fortawesome/fontawesome-svg-core/styles.css'
import "./globals.css";
import InitUser from "./components/init/InitUser";
import InitVoices from "./components/init/InitVoices";

const yeseva = Yeseva_One({
  subsets: ["latin"],
  weight: "400",
  variable: "--font-yeseva",
});

const quicksand = Quicksand({
  subsets: ["latin"],
  weight: ["300", "400", "700"], // Load multiple weights
  variable: "--font-quicksand",
});

const courierPrime = Courier_Prime({
  subsets: ['latin'],
  weight: ['400', '700'], // normal and bold
  variable: '--font-courier-prime',
});

config.autoAddCss = false

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
      <link
          href="ttps://fonts.googleapis.com/css2?family=Courier+Prime:ital,wght@0,400;0,700;1,400;1,700&display=swap"
          rel="stylesheet"
        />
      </head>
      <body className={`${yeseva.variable} ${quicksand.variable} antialiased`}>
        <InitUser />
        <InitVoices />
        {children}
      </body>
    </html>
  );
}
