import type { Metadata } from "next";
import { Geist, Geist_Mono, Yeseva_One, Quicksand } from "next/font/google";
import { config } from '@fortawesome/fontawesome-svg-core'
import '@fortawesome/fontawesome-svg-core/styles.css'
import "./globals.css";

const yeseva = Yeseva_One({
  subsets: ["latin"],
  weight: "400",
  variable: "--font-yeseva",
});

const quicksand = Quicksand({
  subsets: ["latin"],
  weight: ["300", "400", "700"], // Load multiple weights
  variable: "--font-quicksand",
});

config.autoAddCss = false

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${yeseva.variable} ${quicksand.variable} antialiased`}>
        {children}
      </body>
    </html>
  );
}
