import type { Metadata } from "next";
import { Geist, Geist_Mono, Yeseva_One, Quicksand, Courier_Prime } from "next/font/google";
import { config } from '@fortawesome/fontawesome-svg-core'
import '@fortawesome/fontawesome-svg-core/styles.css'
import "./globals.css";
import InitUser from "./components/init/InitUser";
import InitVoices from "./components/init/InitVoices";
import localFont from "next/font/local";

const yeseva = Yeseva_One({
  subsets: ["latin"],
  weight: "400",
  variable: "--font-yeseva",
});

const quicksand = Quicksand({
  subsets: ["latin"],
  weight: ["300", "400", "700"], // Load multiple weights
  variable: "--font-quicksand",
});

const courierPrime = Courier_Prime({
  subsets: ['latin'],
  weight: ['400', '700'], // normal and bold
  variable: '--font-courier-prime',
});

config.autoAddCss = false

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const marlonProBold = localFont({
  src: "../../public/fonts/marlonProBold.ttf",
})

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="h-full overflow-hidden">
      <head>
      </head>
      <body className={`${yeseva.variable} ${quicksand.variable} ${marlonProBold.className} antialiased h-full overflow-hidden`}>
        <InitUser />
        <InitVoices />
        <div id="main-scroll-container" className="h-full pt-[125px] -mt-[125px]">
          {children}
        </div>
      </body>
    </html>
  );
}